import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen grid place-items-center p-4 bg-gradient-to-b from-[#65060D] to-[#9DA0DD]">
          <div className="w-full max-w-lg rounded-2xl border shadow-sm bg-white/90 dark:bg-neutral-900/60 backdrop-blur p-6">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
